# Generated by Django 5.0 on 2024-02-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.TextField()),
                ('short', models.TextField()),
                ('short_viewed', models.CharField(max_length=20)),
            ],
        ),
    ]
